export type Direction = 'BUY' | 'SELL';
export type Bias = 'BULLISH' | 'BEARISH' | 'NEUTRAL';
export type Regime = 'TRENDING BULLISH' | 'TRENDING BEARISH' | 'RANGING' | 'HIGH VOLATILITY' | 'LOW VOLATILITY' | 'UNCERTAIN';

export interface Candle { open: number; high: number; low: number; close: number; volume?: number; time: number; }
export interface TimeframeSnapshot { timeframe: 'H4' | 'H1' | 'M15' | 'M5'; candles: Candle[]; }
export interface StrategySettings { minimumConfidence: number; atrMultiplier: number; targetRR: number; newsFilter: boolean; signalCooldownMinutes: number; weights: { trend: number; structure: number; momentum: number; supportResistance: number; liquidity: number; volatility: number; candle: number; fvg: number }; }
export const defaultStrategySettings: StrategySettings = { minimumConfidence: 70, atrMultiplier: 1.25, targetRR: 2, newsFilter: true, signalCooldownMinutes: 60, weights: { trend: 20, structure: 20, momentum: 15, supportResistance: 15, liquidity: 10, volatility: 5, candle: 10, fvg: 5 } };
export interface IndicatorSnapshot { ema20: number; ema50: number; ema200: number; rsi14: number; macd: number; macdSignal: number; histogram: number; atr14: number; adx14: number; }
export interface Condition { label: string; passed: boolean; points: number; max: number; }
export interface SignalResult { status: 'BUY' | 'SELL' | 'NO TRADE'; direction?: Direction; confidence: number; regime: Regime; entry?: number; stopLoss?: number; takeProfit1?: number; takeProfit2?: number; riskReward?: string; higherTimeframeBias: Bias; timeframe: 'M5' | 'M15'; conditions: Condition[]; explanation: string; reasons: string[]; missing: string[]; generatedAt: number; dataUpdatedAt: number; }

const clamp = (n: number, min = 0, max = 100) => Math.max(min, Math.min(max, n));
const last = (candles: Candle[]) => candles[candles.length - 1];
const sma = (values: number[], period: number) => values.length ? values.slice(-period).reduce((a, b) => a + b, 0) / Math.min(period, values.length) : 0;
export const ema = (values: number[], period: number) => { if (!values.length) return 0; const k = 2 / (period + 1); return values.reduce((acc, value, i) => i ? value * k + acc * (1 - k) : value, values[0]); };
export const calculateAtr = (candles: Candle[], period = 14) => sma(candles.slice(1).map((c, i) => Math.max(c.high - c.low, Math.abs(c.high - candles[i].close), Math.abs(c.low - candles[i].close))), period);
export const calculateRsi = (candles: Candle[], period = 14) => { const changes = candles.slice(1).map((c, i) => c.close - candles[i].close); const gains = changes.map(v => Math.max(v, 0)); const losses = changes.map(v => Math.max(-v, 0)); const loss = sma(losses, period); return loss === 0 ? 100 : 100 - 100 / (1 + sma(gains, period) / loss); };
const calculateAdx = (candles: Candle[], period = 14) => { if (candles.length < period + 1) return 0; const moves = candles.slice(1).map((c, i) => Math.abs(c.close - candles[i].close)); const ranges = candles.slice(1).map((c, i) => Math.max(c.high - c.low, Math.abs(c.high - candles[i].close), Math.abs(c.low - candles[i].close))); return clamp(sma(moves, period) / Math.max(sma(ranges, period), 1e-9) * 100); };
export const calculateIndicators = (candles: Candle[]): IndicatorSnapshot => { const closes = candles.map(c => c.close); const fast = ema(closes, 12); const slow = ema(closes, 26); const macd = fast - slow; const macdSeries = closes.map((_, i) => ema(closes.slice(0, i + 1), 12) - ema(closes.slice(0, i + 1), 26)); const signal = ema(macdSeries, 9); return { ema20: ema(closes, 20), ema50: ema(closes, 50), ema200: ema(closes, 200), rsi14: calculateRsi(candles), macd, macdSignal: signal, histogram: macd - signal, atr14: calculateAtr(candles), adx14: calculateAdx(candles) }; };

export const detectBias = (candles: Candle[]): Bias => { if (candles.length < 20) return 'NEUTRAL'; const i = calculateIndicators(candles); const p = last(candles).close; if (p > i.ema200 && i.ema20 > i.ema50) return 'BULLISH'; if (p < i.ema200 && i.ema20 < i.ema50) return 'BEARISH'; return 'NEUTRAL'; };
export const detectRegime = (candles: Candle[], indicators = calculateIndicators(candles)): Regime => { if (!candles.length || !indicators.atr14) return 'UNCERTAIN'; const ratio = indicators.atr14 / Math.max(last(candles).close, 1e-9); if (ratio > .02) return 'HIGH VOLATILITY'; if (ratio < .001) return 'LOW VOLATILITY'; const bias = detectBias(candles); return bias === 'BULLISH' ? 'TRENDING BULLISH' : bias === 'BEARISH' ? 'TRENDING BEARISH' : 'RANGING'; };

const structure = (candles: Candle[], direction: Direction, max: number): Condition => { const r = candles.slice(-8); if (r.length < 6) return { label: 'Confirmed HH/HL or LL/LH structure', passed: false, points: 0, max }; const up = last(r).high > r[0].high && last(r).low > r[0].low; const down = last(r).high < r[0].high && last(r).low < r[0].low; const passed = direction === 'BUY' ? up : down; return { label: passed ? (direction === 'BUY' ? 'HH / HL + bullish BOS' : 'LL / LH + bearish BOS') : 'Entry structure conflicts with bias', passed, points: passed ? max : 0, max }; };
const levelConfirmation = (candles: Candle[], direction: Direction, max: number): Condition => { const r = candles.slice(-20); const p = last(candles).close; const support = Math.min(...r.slice(0, -1).map(c => c.low)); const resistance = Math.max(...r.slice(0, -1).map(c => c.high)); const range = Math.max(resistance - support, 1e-9); const nearSupport = Math.abs(p - support) < range * .2; const nearResistance = Math.abs(p - resistance) < range * .2; const passed = direction === 'BUY' ? nearSupport || p > resistance : nearResistance || p < support; return { label: direction === 'BUY' ? 'Support / breakout-retest confirmation' : 'Resistance / breakdown-retest confirmation', passed, points: passed ? max : 0, max }; };
const liquidity = (candles: Candle[], direction: Direction, max: number): Condition => { const r = candles.slice(-12); const previousLow = Math.min(...r.slice(0, -2).map(c => c.low)); const previousHigh = Math.max(...r.slice(0, -2).map(c => c.high)); const recent = r.at(-1)!; const sweep = direction === 'BUY' ? recent.low < previousLow && recent.close > previousLow : recent.high > previousHigh && recent.close < previousHigh; return { label: sweep ? (direction === 'BUY' ? 'Sell-side liquidity sweep and rejection' : 'Buy-side liquidity sweep and rejection') : 'No confirmed liquidity sweep', passed: sweep, points: sweep ? max : 0, max }; };
const candleConfirmation = (c: Candle, direction: Direction, max: number): Condition => { const body = Math.abs(c.close - c.open); const range = Math.max(c.high - c.low, 1e-9); const bullish = c.close > c.open && body / range > .35; const bearish = c.close < c.open && body / range > .35; const passed = direction === 'BUY' ? bullish : bearish; return { label: passed ? (direction === 'BUY' ? 'Bullish rejection / engulfing candle' : 'Bearish rejection / engulfing candle') : 'No confirmed candle pattern', passed, points: passed ? max : 0, max }; };
const fvg = (candles: Candle[], direction: Direction, max: number): Condition => { if (candles.length < 3) return { label: 'Relevant FVG / imbalance', passed: false, points: 0, max }; const a = candles.at(-3)!; const c = candles.at(-1)!; const passed = direction === 'BUY' ? c.low > a.high : c.high < a.low; return { label: passed ? (direction === 'BUY' ? 'Bullish FVG / imbalance' : 'Bearish FVG / imbalance') : 'No relevant FVG', passed, points: passed ? max : 0, max }; };

export function analyzeSignal(input: { symbol: string; timeframes: TimeframeSnapshot[]; dataUpdatedAt: number; settings?: StrategySettings; majorNewsBlocked?: boolean; previousSignal?: { direction: Direction; createdAt: number } }): SignalResult {
  const s = input.settings ?? defaultStrategySettings; const get = (tf: TimeframeSnapshot['timeframe']) => input.timeframes.find(x => x.timeframe === tf)?.candles ?? []; const h4 = get('H4'), h1 = get('H1'), m15 = get('M15'), m5 = get('M5'); const entry = m5.length ? m5 : m15; const now = Date.now();
  if (h4.length < 30 || h1.length < 30 || entry.length < 30) return { status: 'NO TRADE', confidence: 0, regime: 'UNCERTAIN', higherTimeframeBias: 'NEUTRAL', timeframe: m5.length ? 'M5' : 'M15', conditions: [], explanation: 'NO TRADE — confirmed H4, H1 and entry candles are required.', reasons: [], missing: ['Market data'], generatedAt: now, dataUpdatedAt: input.dataUpdatedAt };
  const h4Bias = detectBias(h4), h1Bias = detectBias(h1); const bias = h4Bias === h1Bias ? h4Bias : 'NEUTRAL'; const direction: Direction = bias === 'BEARISH' ? 'SELL' : 'BUY'; const i = calculateIndicators(entry); const trend: Condition = { label: `${h4Bias} H4 / ${h1Bias} H1 higher-timeframe trend`, passed: bias !== 'NEUTRAL', points: bias !== 'NEUTRAL' ? s.weights.trend : 0, max: s.weights.trend }; const emaPass = direction === 'BUY' ? last(entry).close > i.ema200 && i.ema20 > i.ema50 : last(entry).close < i.ema200 && i.ema20 < i.ema50; const rsiPass = direction === 'BUY' ? i.rsi14 > 50 && i.rsi14 <= 70 : i.rsi14 < 50 && i.rsi14 >= 30; const macdPass = direction === 'BUY' ? i.histogram > 0 : i.histogram < 0;
  const conditions: Condition[] = [trend, structure(entry, direction, s.weights.structure), { label: direction === 'BUY' ? 'EMA 20 > 50 and price above EMA 200' : 'EMA 20 < 50 and price below EMA 200', passed: emaPass, points: emaPass ? s.weights.momentum * .45 : 0, max: s.weights.momentum * .45 }, { label: `RSI 14 ${i.rsi14.toFixed(1)} supports momentum`, passed: rsiPass, points: rsiPass ? s.weights.momentum * .3 : 0, max: s.weights.momentum * .3 }, { label: 'MACD 12/26/9 confirms momentum', passed: macdPass, points: macdPass ? s.weights.momentum * .25 : 0, max: s.weights.momentum * .25 }, levelConfirmation(entry, direction, s.weights.supportResistance), liquidity(entry, direction, s.weights.liquidity), { label: `ATR 14 / ADX 14 volatility (${i.adx14.toFixed(1)} ADX)`, passed: i.atr14 > 0 && i.adx14 >= 20, points: i.atr14 > 0 && i.adx14 >= 20 ? s.weights.volatility : 0, max: s.weights.volatility }, candleConfirmation(last(entry), direction, s.weights.candle), fvg(entry, direction, s.weights.fvg)];
  const max = conditions.reduce((a, c) => a + c.max, 0); const confidence = Math.round(clamp(conditions.reduce((a, c) => a + c.points, 0) / Math.max(max, 1) * 100)); const duplicate = !!input.previousSignal && input.previousSignal.direction === direction && now - input.previousSignal.createdAt < s.signalCooldownMinutes * 60000; const blocked = !!s.newsFilter && !!input.majorNewsBlocked; const conflicting = bias === 'NEUTRAL' || !conditions[1].passed; const noTrade = duplicate || blocked || conflicting || confidence < s.minimumConfidence; const reasons = conditions.filter(c => c.passed).map(c => c.label); const missing = conditions.filter(c => !c.passed).map(c => c.label); const explanation = noTrade ? `NO TRADE — CONDITIONS NOT ALIGNED. ${conflicting ? 'H4/H1 or entry structure conflict. ' : ''}${blocked ? 'News filter active. ' : ''}${duplicate ? 'Duplicate cooldown active. ' : ''}Score: ${confidence}%.` : `${direction} because ${reasons.join(', ')}.`; const atr = i.atr14; const p = last(entry).close; const swingLow = Math.min(...entry.slice(-10).map(c => c.low)); const swingHigh = Math.max(...entry.slice(-10).map(c => c.high)); const stop = direction === 'BUY' ? swingLow - atr * s.atrMultiplier : swingHigh + atr * s.atrMultiplier; const risk = Math.abs(p - stop); const tp1 = direction === 'BUY' ? p + risk * 1.5 : p - risk * 1.5; const tp2 = direction === 'BUY' ? p + risk * s.targetRR : p - risk * s.targetRR;
  return { status: noTrade ? 'NO TRADE' : direction, direction: noTrade ? undefined : direction, confidence, regime: detectRegime(entry, i), higherTimeframeBias: bias, timeframe: m5.length ? 'M5' : 'M15', conditions, explanation, reasons, missing, entry: noTrade ? undefined : p, stopLoss: noTrade ? undefined : stop, takeProfit1: noTrade ? undefined : tp1, takeProfit2: noTrade ? undefined : tp2, riskReward: noTrade ? undefined : `1:${(Math.abs(tp2 - p) / Math.max(risk, 1e-9)).toFixed(1)}`, generatedAt: now, dataUpdatedAt: input.dataUpdatedAt };
}
